name: lint
on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/mypy-check@master
        with:
          path: 'PORTAL/jobs/*.py'
          python_version: ${{ matrix.python_version }}

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install flake8
        run: |
          pip install flake8
      - uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8' # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
